pipeline {
    agent {
		label ''
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
			sh "cp reports.json $WORKSPACE"
                        cucumber fileIncludePattern: 'reports.json'
                        build job: 'cucumber-report'
                }
            }
        }
	  stage('Generate HTML report') {
		  steps {
                cucumber buildStatus: 'UNSTABLE',
                    reportTitle: 'My report',
                    fileIncludePattern: '**/*.json',
                    trendsLimit: 10,
                    classifications: [
                    [
                        'key': 'Browser',
                        'value': 'Firefox'
                    ]
                ]
		  }
    }
    }
}
