pipeline {
    agent {
		label ''
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    {
stage('Publish Reports') {
echo "***** Publish Reports ***"
	step { 
$class: 'CucumberReportPublisher',
failedFeaturesNumber: 0,
failedScenariosNumber: 0,
failedStepsNumber: 0,
fileExcludePattern: '',
fileIncludePattern: '/*.json’,
jsonReportDirectory: '${workspace}',
parallelTesting: true,
pendingStepsNumber: 0,
skippedStepsNumber: 0,
trendsLimit: 0,
undefinedStepsNumber: 0,
classifications: runClassifications
	}
}
    }
}
