pipeline {
    agent {
		label ''
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
		post{
		always {
			sh "cp cucumber.json ${workspace}"
			cucumber '--format json -o cucumber.json'
		}
		}
        }
    }
}
